import { Injectable } from '@angular/core';
import { of, BehaviorSubject } from 'rxjs';
import { map } from 'rxjs/operators';

const DATA = [
  {"vm_name":"test-imunify-with-save-image","vm_state":1,"cdp_in_process":false,"deleted":false,"deprovision_status":false,"is_active":true,"zabbix_host_id":null,"cdp_enabled":false,"plan":"CentOS-7.3","ip_address_public":"101.53.147.205","reserve_ip_status":false,"reserve_ip_price":"150 Credit Point","terminate_vm_status":false,"vm_id":6726,"id":4617,"customer":783,"agent_id":null,"vm_type":"vm","vcpu":1,"private_cloud_check":false,"label":"Default","scaler_id":null,"is_backup_notify_mail_sent":false,"ip_address_private":"172.16.215.92","lock_status":false,"memory":"2 GB","last_backup_time":null,"template_id":573,"distro":"CentOS-7.3"},
  {"vm_name":"qwerty","vm_state":4,"cdp_in_process":false,"deleted":false,"deprovision_status":false,"is_active":true,"zabbix_host_id":null,"cdp_enabled":false,"plan":"CentOS-7.3","ip_address_public":"101.53.147.249","reserve_ip_status":false,"reserve_ip_price":"150 Credit Point","terminate_vm_status":false,"vm_id":6979,"id":4629,"customer":783,"agent_id":null,"vm_type":"vm","vcpu":1,"private_cloud_check":false,"label":"Default","scaler_id":null,"is_backup_notify_mail_sent":false,"ip_address_private":"172.16.215.88","lock_status":false,"memory":"2 GB","last_backup_time":null,"template_id":573,"distro":"CentOS-7.3"},
  {"vm_name":"plesk-image-testing","vm_state":3,"cdp_in_process":false,"deleted":false,"deprovision_status":false,"is_active":true,"zabbix_host_id":null,"cdp_enabled":false,"plan":"Ubuntu-18.04-kvm","ip_address_public":"101.53.147.201","reserve_ip_status":false,"reserve_ip_price":"150 Credit Point","terminate_vm_status":false,"vm_id":7057,"id":4637,"customer":783,"agent_id":null,"vm_type":"vm","vcpu":4,"private_cloud_check":false,"label":"Default","scaler_id":null,"is_backup_notify_mail_sent":false,"ip_address_private":"172.16.215.71","lock_status":false,"memory":"4 GB","last_backup_time":null,"template_id":557,"distro":"Ubuntu-18.04-kvm"},
  {"vm_name":"imunify-testing","vm_state":1,"cdp_in_process":false,"deleted":false,"deprovision_status":false,"is_active":true,"zabbix_host_id":14843,"cdp_enabled":false,"plan":"Ubuntu-18.04","ip_address_public":"101.53.147.185","reserve_ip_status":false,"reserve_ip_price":"150 Credit Point","terminate_vm_status":false,"vm_id":7158,"id":4642,"customer":783,"agent_id":null,"vm_type":"vm","vcpu":4,"private_cloud_check":false,"label":"Default","scaler_id":null,"is_backup_notify_mail_sent":false,"ip_address_private":"172.16.215.94","lock_status":false,"memory":"4 GB","last_backup_time":null,"template_id":524,"distro":"Ubuntu-18.04"},
  {"vm_name":"plesk-ul-license","vm_state":4,"cdp_in_process":false,"deleted":false,"deprovision_status":false,"is_active":true,"zabbix_host_id":14879,"cdp_enabled":false,"plan":"Ubuntu-18.04","ip_address_public":"101.53.147.210","reserve_ip_status":false,"reserve_ip_price":"150 Credit Point","terminate_vm_status":false,"vm_id":7366,"id":4680,"customer":783,"agent_id":null,"vm_type":"vm","vcpu":4,"private_cloud_check":false,"label":"Default","scaler_id":null,"is_backup_notify_mail_sent":false,"ip_address_private":"172.16.215.163","lock_status":false,"memory":"4 GB","last_backup_time":null,"template_id":557,"distro":"Ubuntu-18.04"},
  {"vm_name":"Main server app","vm_state":3,"cdp_in_process":false,"deleted":false,"deprovision_status":false,"is_active":true,"zabbix_host_id":37938,"cdp_enabled":false,"plan":"C2.8GB-CentOS-7.5","ip_address_public":"164.52.193.125","terminate_vm_status":false,"vm_id":38112,  "id":32325,"customer":7537,"agent_id":null,"vm_type":"vm","vcpu":2,"private_cloud_check":false,"label":"Default","scaler_id":null,"is_backup_notify_mail_sent":true,"ip_address_private":"172.16.114.70","lock_status":false,"memory":"8 GB","last_backup_time":null,"template_id":2630,"distro":"CentOS-7.5"},
  {"vm_name":"main server db","vm_state":4,"cdp_in_process":true,"deleted":false,"deprovision_status":false,"is_active":true,"zabbix_host_id":37939,"cdp_enabled":false,"plan":"C2.8GB-CentOS-7.5","ip_address_public":"164.52.192.127","terminate_vm_status":false,"vm_id":38112,    "id":32327,"customer":7538,"agent_id":null,"vm_type":"vm","vcpu":2,"private_cloud_check":false,"label":"Default","scaler_id":null,"is_backup_notify_mail_sent":true,"ip_address_private":"172.16.114.75","lock_status":false,"memory":"8 GB","last_backup_time":null,"template_id":2630,"distro":"Distro-1.5"},
  {"vm_name":"test","vm_state":5,"cdp_in_process":false,"deleted":false,"deprovision_status":false,"is_active":true,"zabbix_host_id":37938,"cdp_enabled":false,"plan":"C2.8GB-CentOS-7.5","ip_address_public":"164.52.193.345","terminate_vm_status":false,"vm_id":38112,             "id":32345,"customer":7537,"agent_id":null,"vm_type":"vm","vcpu":2,"private_cloud_check":false,"label":"Default","scaler_id":null,"is_backup_notify_mail_sent":true,"ip_address_private":"172.16.114.70","lock_status":false,"memory":"8 GB","last_backup_time":null,"template_id":2630,"distro":"GPU-5"},
  {"vm_name":"virtual","vm_state":0,"cdp_in_process":true,"deleted":false,"deprovision_status":false,"is_active":true,"zabbix_host_id":37939,"cdp_enabled":false,"plan":"C2.8GB-CentOS-7.5","ip_address_public":"164.52.192.177","terminate_vm_status":false,"vm_id":38112,           "id":32377,"customer":7538,"agent_id":null,"vm_type":"vm","vcpu":2,"private_cloud_check":false,"label":"Default","scaler_id":null,"is_backup_notify_mail_sent":true,"ip_address_private":"172.16.114.75","lock_status":false,"memory":"8 GB","last_backup_time":null,"template_id":2630,"distro":"Windows-2019"},
  {"vm_name":"test","vm_state":4,"cdp_in_process":false,"deleted":false,"deprovision_status":false,"is_active":true,"zabbix_host_id":37938,"cdp_enabled":false,"plan":"C2.8GB-CentOS-7.5","ip_address_public":"164.52.193.178","terminate_vm_status":false,"vm_id":38112,             "id":32378,"customer":7537,"agent_id":null,"vm_type":"vm","vcpu":2,"private_cloud_check":false,"label":"Default","scaler_id":null,"is_backup_notify_mail_sent":true,"ip_address_private":"172.16.114.70","lock_status":false,"memory":"8 GB","last_backup_time":null,"template_id":2630,"distro":"CentOS-5.5"},
  {"vm_name":"main server db","vm_state":4,"cdp_in_process":true,"deleted":false,"deprovision_status":false,"is_active":true,"zabbix_host_id":37939,"cdp_enabled":false,"plan":"C2.8GB-CentOS-7.5","ip_address_public":"164.52.192.127","terminate_vm_status":false,"vm_id":38112,    "id":32387,"customer":7538,"agent_id":null,"vm_type":"vm","vcpu":2,"private_cloud_check":false,"label":"Default","scaler_id":null,"is_backup_notify_mail_sent":true,"ip_address_private":"172.16.114.75","lock_status":false,"memory":"8 GB","last_backup_time":null,"template_id":2630,"distro":"Distro-1.5"},
  {"vm_name":"test","vm_state":5,"cdp_in_process":false,"deleted":false,"deprovision_status":false,"is_active":true,"zabbix_host_id":37938,"cdp_enabled":false,"plan":"C2.8GB-CentOS-7.5","ip_address_public":"164.52.193.345","terminate_vm_status":false,"vm_id":38112,              "id":32395,"customer":7537,"agent_id":null,"vm_type":"vm","vcpu":2,"private_cloud_check":false,"label":"Default","scaler_id":null,"is_backup_notify_mail_sent":true,"ip_address_private":"172.16.114.70","lock_status":false,"memory":"8 GB","last_backup_time":null,"template_id":2630,"distro":"GPU-5"},
  {"vm_name":"virtual","vm_state":6,"cdp_in_process":true,"deleted":false,"deprovision_status":false,"is_active":true,"zabbix_host_id":37939,"cdp_enabled":false,"plan":"C2.8GB-CentOS-7.5","ip_address_public":"164.52.192.177","terminate_vm_status":false,"vm_id":38112,            "id":32307,"customer":7538,"agent_id":null,"vm_type":"vm","vcpu":2,"private_cloud_check":false,"label":"Default","scaler_id":null,"is_backup_notify_mail_sent":true,"ip_address_private":"172.16.114.75","lock_status":false,"memory":"8 GB","last_backup_time":null,"template_id":2630,"distro":"Windows-2019"},
  {"vm_name":"main server","vm_state":8,"cdp_in_process":true,"deleted":false,"deprovision_status":false,"is_active":true,"zabbix_host_id":37939,"cdp_enabled":false,"plan":"C2.8GB-CentOS-7.5","ip_address_public":"164.52.192.179","terminate_vm_status":false,"vm_id":38112,        "id":32379,"customer":7538,"agent_id":null,"vm_type":"vm","vcpu":2,"private_cloud_check":false,"label":"Default","scaler_id":null,"is_backup_notify_mail_sent":true,"ip_address_private":"172.16.114.75","lock_status":false,"memory":"8 GB","last_backup_time":null,"template_id":2630,"distro":"Windows-2000"}
];

let nodesObservable = of(DATA);

@Injectable()
export class NodeService {

  getNodes() {
    return nodesObservable;
  }
  getNode(id: any) {
    return nodesObservable.pipe(map(nodes => nodes.find(node => node.id === id)));
  }

  defaultCount = new BehaviorSubject<any>('0');

}
